### ISSUE TITLE
Generates a book folder, but no notes.

### ISSUE THREAD

**Issue by heiders** [Edo78/obsidian-koreader-sync#25] opened 2022-01-27 06:49 UTC
.. somehow the plugin is not importing notes any more. It does see my Kobo, because it generates a folder for each book, but it doesn't make any notes inside the folder. I tried reinstalling the plugin and use the default template, but to no avail.

_Originally posted by @heiders in https://github.com/Edo78/obsidian-koreader-sync/issues/23#issuecomment-1022898328_

**Comment by Edo78** [comment] 2022-01-27 07:24
As stated in the documentation

`Create a folder for each book` if you are a fan of folders enabling this setting the **new notes** will be created in a subfolder named as the book itself

With the default behaviour the existing notes will remain in their location. This is a precise choise, to let the user move their notes as they pleased without fearing an attack of clones :smile: 

If you already have notes in other paths you need to delete them and let the plugin create in the right path or set the `keep_in _sync` property to `true` and the plugin _should_ do it automatically (just realized I never tested this behaviour).

**Comment by heiders** [comment] 2022-01-27 07:55
Yes, I know. I did that a bunch of times yesterday when tinkering with the custom template. But now there are no notes imported or updated anymore. Even if I delete the whole folder, it only generates a folder but without any notes inside. It might be an error on my side, but before the plug-in update it worked fine.

**Comment by Edo78** [comment] 2022-01-27 08:14
I just did some tests and I can't reproduce your error (the closest thing that happens to me was connecting the kobo but forgetting to mount it).

Can you open the developer tools (using Ctrl+Shift+I on Windows/Linux or Cmd+Opt+I on macOS) and do a screenshot of the `Console` tab that shoul have some red errors?

**Comment by heiders** [comment] 2022-01-27 08:19
Like this?
<img width="526" alt="Schermafbeelding 2022-01-27 om 9 17 55 AM" src="https://user-images.githubusercontent.com/4167145/151319296-4f853c3a-7c72-404e-a0b1-2fb5b3a8081b.png">

**Comment by Edo78** [comment] 2022-01-27 08:54
Perfect. It looks like you have a note without text... have you just highlighted something? I never do that so this can explain the behaviour.
It happened after the update because the page number is inside that text so I have to parse it and this time I didn't checkl if it exists.
Bad news if that text is empty I can't get the page number and I'll default to `-1`

BTW a fix is coming.

**Comment by Edo78** [comment] 2022-01-27 09:05
Closed in 0.2.2

**Closed by Edo78** 2022-01-27 09:05 UTC
Labels: bug

**Comment by heiders** [comment] 2022-01-27 09:29
Thanks, update solved it! I very frequently highlight text without adding a note, I prefer adding notes on my laptop, because I don't like using the keyboard on my e-reader.

**Comment by Edo78** [comment] 2022-01-27 10:34
> Thanks, update solved it! I very frequently highlight text without adding a note, I prefer adding notes on my laptop, because I don't like using the keyboard on my e-reader.

I feel your pain, the KOReader keyboard isn't its best feature but I just wrote at least a draft.

BTW happy to have solved the issue
